version: '2'
services:
  db:
    build: ./db
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    hostname: db
    ports:
      - "3306:3306"
  web:
      build: ./web
      ports:
        - '80:80'
      volumes:
        - ./www:/var/www
      depends_on:
        - db
